### ISSUE TITLE
Is this meant to be public

### ISSUE THREAD

**Issue by hisuwh** [NewOrbit/AzureVnetPassSamples#2]
@flytzen Is this repo meant to be public?  Seems to a password and a salt and other things in here you might not want to be public (even if this is just a test thing).

**Comment by flytzen** [comment]
Hi @hisuwh 
Good catch - assume you are referring to the json files in the "infrastructure" folder? Yes, they shouldn't be there, temp files checked in by accident, I will remove. The secrets in there have long since been deleted, but it's confusing to have it there :)
There is also a password in the pulumi script which I should really replace with a random secret being generated. Thanks for raising it.

Yes, it should be public btw, it's an example of sorts.

**Comment by flytzen** [comment]
Fixed
